### ISSUE TITLE
Policies with Filament-Shield 

### ISSUE THREAD

**Issue by R00tes** [ramnzys/filament-email-log#1]
Hello, 
I think that the shield:generate policies are not working. I have problems issues with it. All my users can see it even if I did detach the permissions.

**Comment by ramnzys** [comment]
Hi,

Since this is a Resource from a package, Laravel will not be able to auto discover the generated policy from `sheidl:generate`, you have to assign it directly. 

You can do this in the file `app/Providers/AuthServiceProvider.php`.

```php
use App\Policies\EmailPolicy;  // <--- The policy generated vía shield:generate
use Ramnzys\FilamentEmailLog\Models\Email; // <--- The Email model for the resource
use Illuminate\Foundation\Support\Providers\AuthServiceProvider as ServiceProvider;
use Illuminate\Support\Facades\Gate;

class AuthServiceProvider extends ServiceProvider
{
    /**
     * The model to policy mappings for the application.
     *
     * @var array<class-string, class-string>
     */
    protected $policies = [
        Email::class => EmailPolicy::class,
        // any other policy you may have ...
    ];
```

Hope it helps.

**Comment by R00tes** [comment]
Thanks so much! love it!
